jobs:
  include:
    - stage: Frontend
      language: node_js
      node_js:
        - "node"
      script:
        - npm run lint
    - stage: Backend
      language: python
      python: "3.5"
      install: pip install -r application/requirements.txt
      services: postgresql
      before_script:
        - psql -c 'create database playlistr_test;' -U postgres
      script: 
        - python test.py

notifications:
  slack: csswejusticeleague:zsFlRhEbi7aDPGANxA8tRSoh
