matrix:
  include:
    - language: node_js
      node_js:
        - "node"
      script:
        - npm run lint
  include:
    - language: python
      python: 
        - 3.6
      install: pip install -r requirements.txt
      services: postgresql
      before_script:
        - psql -c 'create database playlistr_test;' -U postgres
      script: 
        - python test.py

notifications:
  slack: csswejusticeleague:zsFlRhEbi7aDPGANxA8tRSoh
