language: node_js
node_js:
  - "node"
python: "3.5"

jobs:
  include:
    - stage: Frontend
      script:
        - npm run lint
    - stage: Backend
      install: pip install -r application/requirements.txt
      services: postgresql
      before_script:
        - psql -c 'create database playlistr_test;' -U postgres
      script: 
        - python test.py

notifications:
  slack: csswejusticeleague:zsFlRhEbi7aDPGANxA8tRSoh
