FORMAT: 1A
HOST: http://hackappellas.apiary.io/

# Playlistr

Playlistr is an API that allows you to pull data for various
types of music. 

## Artists [/artists]

### List Artists [GET]

+ Response 200 (application/json)
        
        {
            "artists": [
                {
                    "id": 1,
                    "name": "Pink Floyd",
                    "genres": [
                        "album rock",
                        "art rock",
                        "classic rock",
                        "mellow gold",
                        "progressive rock",
                        "psychedelic rock",
                        "rock",
                        "space rock",
                        "symphonic rock"
                    ],
                    "imageUrl": "https://i.scdn.co/image/d011c95081cd9a329e506abd7ded47535d524a07",
                    "bio": "Pink Floyd are a psychedelic/progressive rock band formed in Cambridge, England, United Kingdom in 1965. Pink Floyd is one of rock's most successful and influential acts, having sold over 200 million albums worldwide and with 74.5 million certified units in the United States, making them one of the best-selling artists of all time. Currently the band consists of David Gilmour (vocals, guitar) and Nick Mason (drums).\n\nThe band's classic lineup was Roger Waters (vocals <a href=\"https://www.last.fm/music/Pink+Floyd\">Read more on Last.fm</a>",
                    "spotifyUri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9",
                    "playcount": 293729187,
                    "albums": [
                        {
                            id: 1, 
                            name: "The Dark Side of the Moon"
                        },
                        {
                            id: 2, 
                            name: "Wish You Were Here"
                        },
                        {
                            id: 3, 
                            name: "The Wall"
                        }
                    ],
                    "tracks": [
                        {
                            id: 1, 
                            name: "Wish You Were Here"
                        },
                        {
                            id: 2, 
                            name: "Comfortably Numb"
                        },
                        {
                            id: 3, 
                            name: "Another Brick in the Wall"
                        }
                    ],
                }, {
                    "id": 2,
                    "name": "Coldplay",
                    "genres": [
                        "permanent wave",
                        "pop",
                        "pop christmas"
                    ],
                    "imageUrl": "https://i.scdn.co/image/9815eb48540fa0d1c87ebd22289060729b1ab32a",
                    "bio": "Coldplay is a British alternative rock band, formed in London, United Kingdom in 1997. The band comprises vocalist and pianist Chris Martin, lead guitarist Jonny Buckland – who met each other in September 1996 at Ramsay Hall (halls of residence) at University College London - bassist Guy Berryman and drummer Will Champion.\n\nNot only have Coldplay had 7 highly successful studio album releases (all of which reached #1 on the UK album chart) - with their latest 7th studio album released on December 4 <a href=\"https://www.last.fm/music/Coldplay\">Read more on Last.fm</a>",
                    "spotifyUri": "spotify:artist:4gzpq5DPGxSnKTe4SA8HAU",
                    "playcount": 345732045,
                    "albums": [
                        {
                            id: 4, 
                            name: "Ghost Stories"
                        },
                        {
                            id: 5, 
                            name: "X&Y"
                        },
                        {
                            id: 6, 
                            name: "A Head Full Of Dreams"
                        }                
                    ],
                    "tracks": [
                        {
                            id: 4, 
                            name: "Paradise"
                        },
                        {
                            id: 5, 
                            name: "Viva la Vida"
                        },
                        {
                            id: 6, 
                            name: "A Head Full Of Dreams"
                        }  
                    ]
                }
            ],
            "per_page": 2,
            "pages": 2,
            "prev": null,
            "next": 2,
            "page": 1
        }
       
### Get Artist [GET /artists/{id}]

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Pink Floyd",
            "genres": [
                "album rock",
                "art rock",
                "classic rock",
                "mellow gold",
                "progressive rock",
                "psychedelic rock",
                "rock",
                "space rock",
                "symphonic rock"
            ],
            "imageUrl": "https://i.scdn.co/image/d011c95081cd9a329e506abd7ded47535d524a07",
            "bio": "Pink Floyd are a psychedelic/progressive rock band formed in Cambridge, England, United Kingdom in 1965. Pink Floyd is one of rock's most successful and influential acts, having sold over 200 million albums worldwide and with 74.5 million certified units in the United States, making them one of the best-selling artists of all time. Currently the band consists of David Gilmour (vocals, guitar) and Nick Mason (drums).\n\nThe band's classic lineup was Roger Waters (vocals <a href=\"https://www.last.fm/music/Pink+Floyd\">Read more on Last.fm</a>",
            "spotifyUri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9",
            "playcount": 293729187,
            "albums": [
                {
                    id: 1, 
                    name: "The Dark Side of the Moon"
                },
                {
                    id: 2, 
                    name: "Wish You Were Here"
                },
                {
                    id: 3, 
                    name: "The Wall"
                }
            ],
            "tracks": [
                {
                    id: 1, 
                    name: "Wish You Were Here"
                },
                {
                    id: 2, 
                    name: "Comfortably Numb"
                },
                {
                    id: 3, 
                    name: "Another Brick in the Wall"
                }
            ]
        }
            
## Albums [/albums]

### List Albums [GET]

+ Response 200 (application/json)
        
        {
            "albums": [
                {
                    "id": 1,
                    "name": "The Dark Side of the Moon",
                    "genres": [
                        "album rock",
                        "art rock",
                        "classic rock",
                        "mellow gold",
                        "progressive rock",
                        "psychedelic rock",
                        "rock",
                        "space rock",
                        "symphonic rock"
                    ],
                    "imageUrl": "https://i.scdn.co/image/79b9f90d29978a2edd82c8cdbfd3f091207931c7",
                    "releaseDate": "Wed, 31 Dec 1969 18:00:00 GMT",
                    "playcount": 35925474,
                    "spotifyUri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9",
                    "tracks": [
                        {
                            id: 7, 
                            name: "Speak to Me"
                        },
                        {
                            id: 8, 
                            name: "On the Run"
                        },
                        {
                            id: 9, 
                            name: "Money"
                        }
                    ],
                    "artist": { 
                        id: 1
                        name: "Pink Floyd"
                    }
                }, {
                    "id": 2,
                    "name": "A Head Full Of Dreams",
                    "genres": [
                        "permanent wave",
                        "pop",
                        "pop christmas"
                    ],
                    "imageUrl": "https://i.scdn.co/image/9c2c4a9ac9726bfd996ff96383178bbb5efc59ab",
                    "releaseDate": "Wed, 31 Dec 1969 18:00:00 GMT",
                    "playcount": 6415779,
                    "spotifyUri": "spotify:artist:4gzpq5DPGxSnKTe4SA8HAU",
                    "tracks": [
                        {
                            id: 6, 
                            name: "A Head Full Of Dreams"
                        },
                        {
                            id: 10, 
                            name: "Everglow"
                        },
                        {
                            id: 11, 
                            name: "Fun"
                        }
                    ],
                    "artist": {
                        id: 2
                        name: "Coldplay"
                    }
                }
            ],
            "per_page": 2,
            "pages": 2,
            "prev": null,
            "next": 2,
            "page": 1
        }
        
### Get Album [GET /albums/{id}]

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "The Dark Side Of The Moon",
            "genres": [
                "album rock",
                "art rock",
                "classic rock",
                "mellow gold",
                "progressive rock",
                "psychedelic rock",
                "rock",
                "space rock",
                "symphonic rock"
            ],
            "imageUrl": "https://i.scdn.co/image/79b9f90d29978a2edd82c8cdbfd3f091207931c7",
            "releaseDate": "Wed, 31 Dec 1969 18:00:00 GMT",
            "playcount": 35925474,
            "spotifyUri": "spotify:artist:0k17h0D3J5VfsdmQ1iZtE9",
            "tracks": [
                {
                    id: 7, 
                    name: "Speak to Me"
                },
                {
                    id: 8, 
                    name: "On the Run"
                },
                {
                    id: 9, 
                    name: "Money"
                }
            ],
            "artist": { 
                id: 1
                name: "Pink Floyd"
            }
        }
        
## Tracks [/tracks]

### List Tracks [GET]

+ Response 200 (application/json)
        
        {
            "tracks":
                [
                    {
                        "id": 1,
                        "name": "Money",
                        "playcount": 6851637,
                        "imageUrl":  "https://i.scdn.co/image/79b9f90d29978a2edd82c8cdbfd3f091207931c7",
                        "duration": 382834,
                        "youtubeId": "https://www.youtube.com/watch?v=-0kcet4aPpQ",
                        "spotifyUri": "spotify:track:0vFOzaXqZHahrZp6enQwQb",
                        "artist": { 
                            id: 1
                            name: "Pink Floyd"
                        },
                        "album": {
                            id: 1, 
                            name: "The Dark Side of the Moon"
                        }
                    }, {
                        "id": 2,
                        "name": "A Head Full Of Dreams",
                        "playcount": "",
                        "imageUrl": "https://i.scdn.co/image/9c2c4a9ac9726bfd996ff96383178bbb5efc59ab",
                        "duration": 223773,
                        "youtubeId": "https://www.youtube.com/watch?v=vGZMvV9KBp8",
                        "spotifyUri": "spotify:track:6f49kbOuQSOsStBpyGvQfA",
                        "artist": { 
                            id: 2
                            name: "Coldplay"
                        },
                        "album": {
                            id: 6, 
                            name: "A Head Full of Dreams"
                        }
                    }
                ],
            "per_page": 2,
            "pages": 2,
            "prev": null,
            "next": 2,
            "page": 1
        }
        
### Get Track [GET /tracks/{id}]

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Money",
            "playcount": 6851637,
            "imageUrl": "https://i.scdn.co/image/79b9f90d29978a2edd82c8cdbfd3f091207931c7",
            "duration": 382834,
            "spotifyUri": "spotify:track:0vFOzaXqZHahrZp6enQwQb",
            "artist": { 
                id: 1
                name: "Pink Floyd"
            },
            "album": {
                id: 1, 
                name: "The Dark Side of the Moon"
            }
        }
        
## Playlists [/playlists]

### List Playlists [GET]

+ Response 200 (application/json)
        
        {
            "playlists": [
                {
                    "id": 1,
                    "name": "Transcendental Psych",
                    "numFollowers": 0,
                    "imageUrl": "https://i.scdn.co/image/eed15df0d0849836293b9f787fabf077ce9e9f2e",
                    "spotifyUri": "spotify:user:kshitijmd:playlist:1f5CiyJY5TqfTjhN8VApZV",
                    "artists": [
                        { 
                            id: 1
                            name: "Pink Floyd"
                        },
                        { 
                            id: 3
                            name: "Hans Zimmer"
                        }
                    ],
                    "numArtists": 2,
                    "tracks": [
                        {
                            id: 12, 
                            name: "Any Colour You Like"
                        },
                        {
                            id: 13, 
                            name: "Cornfield Chase"
                        },
                        {
                            id: 14, 
                            name: "Day One"
                        }                            
                    ],
                    "numTracks": 3,
                    "totalDuration": 540000
                }, {
                    "id": 2,
                    "name": "Temporary Wave",
                    "numFollowers": 0
                    "imageUrl": "https://i.scdn.co/image/9c2c4a9ac9726bfd996ff96383178bbb5efc59ab",
                    "spotifyUri": "spotify:user:kshitijmd:playlist:7Jth72BcjMAOHzNnax6mmK",
                    "artists": [
                        { 
                            id: 2
                            name: "Coldplay"
                        },
                        { 
                            id: 3
                            name: "Hans Zimmer"
                        }
                    ],
                    "numArtists": 2,
                    "tracks": [
                        {
                            id: 6, 
                            name: "A Head Full Of Dreams"
                        },
                        {
                            id: 15, 
                            name: "Hymn For The Weekend"
                        },
                        {
                            id: 16, 
                            name: "Dust"
                        }                            
                    ],
                    "numTracks": 3,
                    "totalDuration": 540000
                }
            ],
            "per_page": 2,
            "pages": 2,
            "prev": null,
            "next": 2,
            "page": 1
        }
        
### Get Playlist [GET /playlists/{id}]

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Transcendental Psych",
            "numFollowers": 0,
            "imageUrl": "https://i.scdn.co/image/eed15df0d0849836293b9f787fabf077ce9e9f2e",
            "spotifyUri": "spotify:user:kshitijmd:playlist:1f5CiyJY5TqfTjhN8VApZV",
            "artists": [
                { 
                    id: 1
                    name: "Pink Floyd"
                },
                { 
                    id: 3
                    name: "Hans Zimmer"
                }
            ],
            "numArtists": 2,
            "tracks": [
                {
                    id: 12, 
                    name: "Any Colour You Like"
                },
                {
                    id: 13, 
                    name: "Cornfield Chase"
                },
                {
                    id: 14, 
                    name: "Day One"
                }
            ],
            "numTracks": 3,
            "totalDuration": 540000
        }

## Search [/search]

### Search All [GET]

+ Response 200 (application/json)
        
        {
            "albums": [],
            "artists": [],
            "tracks": [],
            "playlists": []
        }
